version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ponti_rabbit
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass

  mongodb:
    image : mongo
    container_name: ponti_mongo
    environment:
      - PUID=1000
      - PGID=1000
    ports:
        - 27017:27017
    restart: unless-stopped
    
  redis:
    image: "redis:alpine"
    container_name: ponti-redis
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master
  postgres:
    image: postgres:latest
    container_name: ponti_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
